#+title:Pactos de jurisdição assimétricos, sua admissibilidade, validade substancial e interpretação: comentário ao Acórdão do Tribunal de Justiça da União Europeia de 27 de fevereiro de 2025, /Società Italiana Lastre/, C-537/23, EU:C:2025:120
#+title: Asymmetrical jurisdiction pacts, their admissibility, substantive validity and interpretation: annotation on the European Court of Justice Judgment of 27 February 2025, /Società Italiana Lastre/, C-537/23, EU:C:2025:120
#+author: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil date:nil

#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{titletoc}
#+LATEX_HEADER: \KOMAoptions{headings=small}

#+ODT_STYLES_FILE: "~/Dropbox/Bibliografia/ODT/modelo.odt"

#+bibliography: ~/Dropbox/Bibliografia/BetterBibLatex/bib.bib
#+cite_export: csl chicago-fullnote-bibliography.csl

*Resumo:*

*Palavras-chave:* Regulamento Bruxelas I /bis/; competência internacional; pactos de jurisdição assimétricos; validade substancial; interpretação.

*Abstract:*

*Keywords:* Brussels Ia; jurisdiction; asymetrical jurisdiction pacts; substancial validaty; interpretation.

*Sumário:* 1. Os factos do caso; 2. As questões prejudiciais; 3. A resposta do Tribunal de Justiça da União Europeia; 4. Análise; 5.Conclusões.

* 1. Os factos do caso
A empresa Agora, para realização de uma obra encomendada por duas pessoas singulares, celebrou um contrato de fornecimento de painéis de revestimento com a empresa SIL[fn:1]. Este contrato incluía um pacto de jurisdição, no qual se estipulava:
#+begin_quote
«[o] tribunal de Brescia [(Itália)] é competente para qualquer litígio que surja ou que esteja relacionado com o presente contrato[, a SIL] reserva-se o direito de
intentar uma ação contra o comprador noutro tribunal competente em Itália ou no estrangeiro»[fn:2].
#+end_quote

Após terem detetado irregularidades na execução da obra em causa, os donos da obra intentaram, uma ação de indemnização contra a Agora e a SIL no /tribunal de grande instance de Rennes/ (Tribunal de Primeira Instância de Rennes, França)[fn:3]. A Agora requereu a intervenção da SIL como garante. A SIL opôs-se a este pedido, invocando uma exceção dilatória de incompetência internacional do tribunal francês, com fundamento no pacto de jurisdição constante do contrato celebrado entre as duas empresas. A SIL interpôs recurso[fn:4].

O /tribunal de grande instance de Rennes/ (Tribunal de Primeira Instância de Rennes) julgou improcedente esta exceção dilatória de incompetência[fn:5]. A /cour d’appel de Rennes/ (Tribunal de Recurso de Rennes, França), sem examinar a validade da cláusula de atribuição em causa à luz do direito italiano, confirmou a referida decisão com o fundamento de que o pacto atributivo de jurisdição em causa era ilícito, considerando que o mesmo era impreciso e conferia à SIL uma escolha discricionária, contrária ao objetivo de previsibilidade que as cláusulas atributivas de jurisdição devem satisfazer[fn:6].

Inconformada, a SIL recorreu para a /Cour de Cassation/, alegando violação do artigo 25.º, n.º 1, do Regulamento Bruxelas I /bis/[fn:9], uma vez que a validade
de um pacto atributivo de jurisdição deve ser apreciada à luz do direito do Estado-Membro no qual se situam os tribunais designados ao abrigo desse pacto e, portanto, no caso vertente, à luz do direito italiano[fn:7].

* 2. As questões prejudiciais
A /Cour de Cassation/ decidiu colocar ao Tribunal de Justiça da União Europeia as seguintes questões prejudiciais:

#+begin_quote
1) Perante uma cláusula atributiva de jurisdição assimétrica que só oferece a uma das partes a possibilidade de escolher um tribunal da sua preferência, competente segundo as regras de direito comum, mas diferente do mencionado nessa cláusula, e se a outra parte alegar que esta cláusula é ilegal devido à sua imprecisão e/ou ao seu desequilíbrio, deve esta questão ser decidida à luz de regras autónomas decorrentes do artigo 25.º, n.º 1 do [Regulamento Bruxelas I-A], e do objetivo de previsibilidade e de segurança jurídica prosseguido por este regulamento, ou por aplicação da lei do Estado-Membro designado pela cláusula[?] Por outras palavras, está esta questão relacionada com a validade substantiva da cláusula na aceção daquela disposição ou devem, pelo contrário, os requisitos de validade substantiva da cláusula ser interpretados de forma restritiva no sentido de que apenas dizem respeito às causas materiais de nulidade, principalmente à fraude, ao erro, ao dolo, à violência e à incapacidade?

2) Caso a questão da imprecisão ou do desequilíbrio da cláusula deva ser apreciada à luz de normas autónomas, deve o artigo 25.º, n.º 1, do Regulamento Bruxelas I-A ser interpretado no sentido de que há que aplicar uma cláusula que autoriza uma parte a recorrer a um único tribunal, embora permita à outra parte recorrer a qualquer outro tribunal competente nos termos do direito comum, e não só àquele tribunal, ou deve interpretar-se essa disposição no sentido de que não há que aplicar a referida cláusula?

3) Caso a assimetria de uma cláusula diga respeito a um requisito material, como deve ser interpretada aquela disposição e, em especial, a remissão para a lei do Estado-Membro do tribunal designado, quando vários tribunais forem designados pela cláusula ou quando a cláusula designar um tribunal deixando a uma das partes a possibilidade de escolher outro tribunal e esta escolha ainda não tiver sido feita na data em que o tribunal é chamado a pronunciar-se:

   — a lei nacional aplicável é a lei do único tribunal expressamente designado, independentemente de outros também poderem ser chamados a pronunciar-se?

   — se forem designados vários tribunais, é possível fazer referência à lei do tribunal efetivamente chamado a pronunciar-se?

   — por último, à luz do considerando 20 do Regulamento Bruxelas I-A, deve a remissão para a lei do tribunal do Estado-Membro designado ser entendida como uma remissão para as normas materiais desse Estado ou para as suas normas de conflitos de leis?[fn:8]
#+end_quote

* 3. A resposta do Tribunal de Justiça da União Europeia
Quanto à primeira questão, o O TJ inicia a sua resposta assinalando que o conceito "sustantivamente nulo" não é definido no Regulamento Bruxelas I /bis/. Inexistindo uma remissão para o Direito dos Estados-Membros para determinar o seu sentido e alcance, o TJ recorda a sua jurisprudência constante de que os conceitos devem ser objeto de interpretação autónoma, tendo em conta o sentido habitual desses termos na linguagem corrente, o contexto em que são utilizados e os objetivos prosseguidos pelo instrumento normativo em que estão consagrados[fn:10].

Analisando o elemento literal, o TJ conclui que a expressão "substantivamente" tem, no domínio forense, o sentido habitual de que se refere às questões relativas ao próprio objeto do processo judicial, à relação material controvertida[fn:11]. Alargando à sua análise à parte final do artigo 25.º, n.º 1, conclui que a mesma é uma norma de conflitos que visa determinar o direito material aplicável "à questão de saber se, apesar de todas as condições de validade previstas nesse artigo estarem reunidas, tal pacto é nulo por outros motivos abrangidos por esse direito nacional"[fn:12].

A nível do contexto, o TJ assinala que o considerando n.º 20 do Regulamento Bruxelas I /bis/ este redigido em moldes análogos ao artigo 25.º, n.º 1, e que este artigo, derrogando o princípio geral /actor sequitur forum rei/, deve ser objeto de uma interpretação estrita[fn:13]. Observando o artigo 25.º, n.º 1, globalmente, o TJ assinala que esta disposição prevê condições de validade material e formal próprias dos pactos de jurisdição. Deste modo, a expressão "substantivamente nulo" não abrange às condições validade próprias, mas apenas as causas gerais de nulidade de um contrato, como o erro, o dolo ou a violência, e a incapacidade de contratar[fn:14].

O TJ afirma depois que esta interpretação é conforme aos objetivos prosseguidos pelo Regulamento Bruxelas I /bis/, em particular o de reforço da segurança jurídica, destacando que este objetivo "exige que o juiz nacional ao qual a questão foi submetida possa facilmente pronunciar-se sobre a sua própria competência, sem ser obrigado a proceder a um exame do processo quanto ao mérito"[fn:15]. Assinala também que a interpretação de que a expressão "substantivamente nulo" não abrange às condições validade próprias, mas apenas as causas gerais de nulidade de um contrato, é conforme à sua génese, pois com a introdução desta norma de conflitos visou-se aproximar o regime dos pactos de jurisdição do Regulamento Bruxelas I /bis/ do constante na Convenção da Haia de 2005 sobre os Acordos de Eleição do Foro[fn:16].

Terminada a interpretação autónoma da expressão "substantivamente nulo", o TJ foca-se nos alegados vícios do pacto de jurisdição firmado entre as partes, a saber: a sua alegada imprecisão e o seu alegado desiquilíbrio. No que se refere à alegada imprecisão, o TJ - recorrendo aos Acórdãos de 9 de novembro de 2000, /Coreck Maritime/, C-387/98, EU:C:2000:606, n.º 15, e de 7 de julho de 2016, /Hőszig/, C-222/15, EU:C:2016:525, n.º 43, proferidos, respetivamente, em sede da Convenção de Bruxelas e do Regulamento Bruxelas I e transponíveis para o Regulamento Bruxelas I /bis/ - conclui que o artigo 25.º, n.º 1, contém uma exigência própria de precisão, pelo que, "para ser válido, um pacto atributivo de jurisdição deve nomeadamente identificar, de forma suficientemente precisa, os elementos objetivos sobre os quais as partes chegaram
a acordo para designar o tribunal ou os tribunais aos quais pretendem submeter os seus litígios surgidos ou a surgir"[fn:17]. Quanto ao alegado desequilíbrio, decorrente do seu carácter assimétrico, o TJ conclui que os artigos 15.º, 19.º, 23.º e 25.º, n.º 4, consagram os critérios autónomos do Regulamento Bruxelas I /bis/ para determinar a validade ou invalidade de pactos assimétricos[fn:18]. Considera ainda que este entendimento não é prejudicado pelo facto de a Convenção de Bruxelas conter, ao contrário dos Regulamentos Bruxelas e Bruxelas I /bis/, uma disposição que implicitamente admite a validade de um pacto de jurisdição assimétrico, uma vez que a supressão da norma não visou uma alteração de regime, mas apenas acentuar que a competência atribuida pelo pacto de jurisdição é exclusiva, caso as partes não acordem diversamente[fn:20]. Conclui, por isso, que nenhum dos alegados vícios deve ser avaliados à luz da norma de conflitos constante do artigo 25.º, n.º 1, primeiro período, parte final, mas sim segundo os critérios autónomos do Regulamento Bruxelas I /bis/[fn:19] e, como tal, fica prejudicada a resposta à terceira questão prejudicial[fn:21].

Com a segunda questão prejudicial, o órgão judicial de reenvio pergunta, em síntese, se os critérios autónomos de validade dos pactos de jurisdição do Regulamento de Bruxelas I /bis/ se opõem a um pacto como o que foi firmado entre as partes, com fundamento na alegada imprecisão e ou desequilíbrio (carácter assimétrico) do mesmo.

Analisando o pacto de jurisdição firmado entre as partes, o TJ refere que o mesmo parece permitir a uma das partes recorrer a tribunais de diferentes Estados e esclarece que apesar da redação da norma ("um tribunal ou os tribunais de /um/ Estado-Membro"), o artigo 25.º, n.º 1, não pode ser interpretado no sentido de que apenas permite a escolha de /um/ tribunais ou de /vários ou todos os/ tribunais de /um único/ Estado-Membro, pois tal interpretação seria contrária ao princípio da autonomia privada, subjacente à disposição, e resulta, desde logo, das restantes regras de competência internacional do Regulamento Bruxelas I /bis/, em particular as relativas aos pactos de jurisdição em matéria de seguros, contratos de consumo e contratos individuais de trabalho, a possibilidade de serem internacionalmente competentes para julgar a causa os tribunais de mais do que um Estado-Membro[fn:22].

Quanto ao alegado vício de imprecisão, o TJ salienta que cumpre a exigência de precisão prevista no artigo 25.º, n.º 1, o pacto de jurisdição que designa, "por um lado, um tribunal em particular e, por outro lado, outros tribunais competentes ao abrigo das disposições do capítulo II, secções 1 e 2, do Regulamento Bruxelas I-A e do título II, secções 1 e 2, desta convenção [Convenção Lugano II]", pois esta última parte tratar-se-ia de uma remissão para as regras gerais desses instrumentos normativos[fn:23]. O TJ precisa, porém, que se o trecho "outro tribunal competente [...] no estrangeiro" for interpretado no sentido de que designa também um ou vários Estados que não são membros da União nem partes na Conveção Lugano II, então este pacto seria contrário ao artigo 25.º, n.º 1[fn:24]. Conclui, por isso, que "o pacto atributivo de jurisdição em causa só é suscetível de responder à exigência de precisão, à luz da jurisprudência mencionada no n.º 42 do presente acórdão, na medida em que possa ser interpretado no sentido de que designa o tribunal de Brescia e os tribunais competentes dos Estados-Membros ou dos Estados parte na Convenção de Lugano II para conhecer dos litígios entre as partes"[fn:25].

No que respeita ao carácter assimétrico do pacto de jurisdição, o TJ assinala que o regime dos pactos de jurisdição expressos do Regulamento Bruxelas I /bis/ tem por base o princípio da autonomia privada das partes (cf. assinalado nos anteriores Acórdãos de 9 de novembro de 2000, /Coreck Maritime/, C-387/98, EU:C:2000:606, considerando n.º 14, de 7 de fevereiro de 2013, /Refcomp/, C-543/10, EU:C:2013:62, considerando n.º 26 e de 18 de novembro de 2020, /DelayFix/, C-519/19, EU:C:2020:933, considerando n.º 38) e que resulta do considerando n.º 19 do Regulamento que o legislador da União Europeia entendeu privilegiar o respeito por este princípio. Por esse motivo, um pacto de jurisdição assimétrico livremente acordado pelas partes não é contrário ao regime do Regulamento Bruxelas I /bis/, salvo nos casos em que se viole as regras sobre a celebração de pactos assimétricos em matéria de seguros, contratos de consumo ou contratos individuais de trabalho (artigos 15.º, 19.º e 23.º), ou as regras de competência internacional exclusivas (artigo 24.º)[fn:26].

* 4. Análise

A questão da validade de pactos de jurisdição assimétricos há muito vinha sendo discutida na jurisprudência francesa. Primeiramente, um pacto de jurisdição assimétrico, estipulando que o cliente do banco deveria intentar (eventuais) ações junto dos tribunais do Luxemburgo, podendo o banco intentar (eventuais) ações junto dos tribunais do domicílio do cliente ou perante qualquer outro tribunal competente, foi afastado, tendo a /Cour de Cassation/ considerado que o carácter potestativo da cláusula (em favor do banco) era contrário ao objeto e finalidades do artigo 23.º do Regulamento Bruxelas I[fn:27] [fn:28]. Posteriormente, a /Cour de Cassation/ foi chamada a pronunciar-se sobre um pacto de jurisdição assimétrico em que se estipulava a competência exclusiva dos tribunais do Luxemburgo, reservando a uma das partes (o banco) o direito de afastar o pacto quando o considerasse oportuno. Neste caso, a /Cour de Cassation/ considerou que o requisito de previsibilidade do artigo 23.º do Regulamento Bruxelas I se encontrava preenchido, pois mesmo nos casos em que o banco exercesse o seu direito de afastar o pacto de jurisdição assimétrico, a competência internacional teria de ser determinada nos termos do artigo 5.º, n.º 1, do Regulamento Bruxelas I[fn:29].

É, essencialmente, este o contexto das perguntas colocadas pela /Cour de Cassation/ no reenvio prejudicial, conjugado com a nova norma de conflitos em matéria de validade substancial do pacto, introduzida pelo Regulamento Bruxelas I /bis/.

A /Cour de Cassation/ questionou, em primeiro lugar, se a validade de pactos de jurisdição assimétricos decorrente da sua imprecisão ou desiquilíbrio deve ser aferida segundo os requisitos autónomos do artigo 25.º ou segundo o Direito material do tribunal escolhido, nos termos da norma de conflitos em matéria de validade substancial constante da mesma norma.

Para responder à questão, o TJ procedeu à interpretação do conceito operativo da norma de conflitos introduzida no artigo 25.º, o conceito de "substantivamente nulo". Recordando a sua jurisprudência constante, interpretou autonomamente o conceito, concluindo que este /não abrange/ as condições validade próprias, /mas apenas/ as causas gerais de nulidade de um contrato, como o erro, o dolo ou a violência, e a incapacidade de contratar. Esta conclusão parece-nos particularmente relevante para os objetivos de certeza e previsibilidade jurídicas prosseguidos pelo regime europeu de prorrogação de competência e também para o objetivo declarado da introdução da norma de conflitos: a aproximação ao regime consagrado na Convenção da Haia de 2005 sobre os Acordos de Eleição do Foro.

O TJ concluíu, depois, que os (alegados) vícios de imprecisão e de desiquilíbrio entre as partes do pacto de jurisdição assimétrico respeitam a requisitos autónomos estabelecidos no Regulamento Bruxelas I /bis/.

No que respeita ao (alegado) vício de desequilíbrio entre as partes, o TJ recorda que o regime europeu de prorrogação de competência assenta no princípio da autonomia privada. Para determinar se um pacto de jurisdição assimétrico é válido (apesar do desequilíbrio no que respeita aos direitos e obrigações das partes), o TJ adota um teste tripartido, concluindo que pela validade do pacto se este: /(i)/ não violar competências exclusivas (previstas no artigo 24.º); /(ii)/ não violar as regras sobre a celebração de pactos assimétricos em matéria de seguros, contratos de consumo ou contratos individuais de trabalho (artigos 15.º, 19.º e 23.º); e /(iii)/ for livremente consentido pelas partes.

Os primeiros dois critérios do teste adotado não suscitam questões de maior. O requisito de não violação das competências exclusivas é, na verdade, um requisito autónomo de todo e qualquer pacto de jurisdição (assimétrico ou não) e decorre da prevalência das normas atribuitivas de competência internacional exclusiva sobre as demais normas atributivas de competência internacional do Regulamento Bruxelas I /bis/. No contexto de contratos celebrados com partes vulneráveis, o Regulamento Bruxelas I /bis/ regulou a matéria dos pactos de jurisdição atendendo ao desequilíbrio das partes, razão pela qual a validade um pacto de jurisdição (assimétrico ou não) em matéria de seguros, contratos de consumo ou contratos individuais de trabalho terá de respeitar, respetivamente, o disposto nos artigos 15.º, 19.º e 23.º.

Pode perguntar-se se o terceiro critério - o pacto de jurisdição assimétrico será lícito se /livremente consentido/ pelas partes - estabelece alguma exigência adicional na formação do pacto? A questão compreende-se à luz do debate existente em sede da /electio iuris/ em matéria de obrigações extracontratuais, pois aí se consagrou a exigência de a escolha de lei ser /"livremente negociada"/ nos casos em que seja efetuada em momento anterior ao facto danoso (artigo 14.º, n.º 1, al. /b)/ do Regulamento Roma II[fn:30]). Entendemos, porém, que a resposta a esta questão deve ser negativa. O âmbito de aplicação material do Regulamento Bruxelas I /bis/ (e, por consequência, do seu artigo 25.º) é bastante mais amplo do que o do Regulamento Roma II e abrange também as obrigações contratuais (matéria na qual o exercício da escolha de jurisdição e da lei aplicável tem maior tradição e prevalência). A /electio iuris/ em matéria de obrigações contratuais internacionais não prevê idêntica exigência (artigo 3.º do Regulamento Roma I). Acresce que o TJ, nos considerandos 65 a 67 do Acórdão em comentário, apesar de salvaguardar que se trata de tarefa a efetuar pelo tribunal nacional, aplica o teste tripartido ao pacto de jurisdição assimétrico em apreço sem efetuar quaisquer considerações sobre se o mesmo foi (ou não) livremente consentido pelas partes. Tal aponta no sentido de que essa formulação não visou criar exigências adicionais, mas apenas referenciar o requisito autónomo já estabelecido pela anterior jurisprudência do TJ de que pacto de jurisdição (assimétrico ou não) só é válido se foi efectivamente objecto de consenso entre as partes[fn:31].

No que respeita ao (alegado) vício de imprecisão, é decisivo interpretar o pacto de jurisdição assimétrico. Partindo da sua anterior jurisprudência sobre a exigência de precisão e aplicando-a ao pacto de jurisdição assimétrico em apreço, o TJ tem o cuidado de referir duas interpretações possíveis para a parte final da cláusula "(...) [, a SIL] reserva-se o direito de intentar uma ação contra o comprador noutro tribunal competente em Itália ou no estrangeiro". Se o trecho for entendido como uma remissão para as demais normas atributivas de competência internacional do Regulamento Bruxelas I /bis/ ou da Convenção de Lugano II, o pacto, tal como foi convencionado, cumpre a exigência de precisão. Porém, se o trecho for intepretado como conferindo a essa parte a possibilidade de intentar a ação em Estados terceiros (que não são Estados-Membros ou Estados Contratantes da Convenção de Lugano II), então o pacto violaria os objetivos de previsibilidade, de transparência e de segurança jurídica referidos nos considerandos 15 e 16 do Regulamento Bruxelas I /bis/ (pois as normas do Regulamento Bruxelas I /bis/ ou da Convenção de Lugano II /não seriam suficientes/ para determinar quais os tribunais internacionalmente competentes ao abrigo do pacto) e existiria um risco de soluções divergentes resultantes da aplicação de outras normas atributivas de competência internacional vigente no Estado do foro. Nesse caso, afirmamos nós, não estaria igualmente preenchida uma /outra/ condição de válidade própria, pois o pacto designaria como competente um tribunal de um Estado que não era um Estado-Membro (no caso do Regulamento Bruxelas I /bis/) nem um Estado Contratante (no caso da Convenção de Lugano II).

O TJ, na sua resposta, alargou o âmbito à Convenção de Lugano II, o que merece uma breve referência. À luz do mecanismo de reenvio prejudicial e das questões efetivamente colocadas, o TJ não estava obrigado a pronunciar-se em sede da Convenção de Lugano II. Fê-lo, pensa-se, porque os regimes são substancialmente idênticos no que respeita à exigência de previsão e por força das competências que lhe foram atribuídas ao TJ pelo Protocolo n.º 2, relativo à interpretação uniforme da presente convenção e ao Comité Permanente, anexo à Convenção de Lugano II. Assinala-se, ainda assim, que há diferenças no regime de prorrogação de competência do Regulamento Bruxelas I /bis/ e da Convenção de Lugano II (uma das mais significativas, a norma de conflitos em matéria de validade substancial do artigo 25.º do Regulamento Bruxelas I /bis/) e que, no contexto dos pactos de jurisdição, a Convenção de Lugano II aplicar-se-á, quando o litígio seja dirimido no tribunal de um Estado-Membro, nos casos em que o pacto designe um Estado Contratante, que não seja simultaneamente um Estado-Membro.

No que respeita à interpretação do pacto, recorda-se que, segundo a jurisprudência constante do TJ, a interpretação do pacto de jurisdição compete  ao juiz nacional perante o qual o mesmo é invocado[fn:40]. Apesar disso, no Acórdão sob comentário, o TJ avança duas interpretações possíveis, atento o teor literal do pacto de jurisdição assimétrico em apreço, mas não se pronuncia[fn:41] sobre quais deveriam ser os critérios interpretativos desse negócio jurídico, se critérios autónomos a deduzir do Regulamento Bruxelas I /bis/ (ou do Direito da União Europeia) ou a determinar segundo a lei reguladora da interpretação dos pactos de jurisdição[cite:A questão é discutida na doutrina. Magnus /in/ @magnus2023, artigo 25.º, notas de margem 141 a 143, advoga em favor de critérios de interpretação autónomos do pacto, apenas admitindo subsidiariamente o recurso ao Direito de conflitos do foro e sustentando a aplicação analógica do Regulamento Roma I *inserir mais doutrina*].

A /Cour de Cassation/, na sequência da Acórdão em comentário, considerou que o TJ reenviava a questão para o órgão jurisdicional nacional, que deveria interpretar a cláusula de acordo com os princípios da autonomia privada e do /effet utile/. E, relevando que a situação material subjacente não tinha qualquer conexão objetiva com Estados que não fossem Estados-Membros ou Estados-Contratantes da Convenção de Lugano II, interpretou a cláusula como sendo uma remissão para as demais regras de competência internacional desses dois instrumentos[fn:32]. Esta linha argumentativa suscita dúvidas, porque há muito se assinala que podem existir razões para escolher uma jurisdição que não tenha qualquer conexão objetiva com a relação material subjacente ou as partes, designadamente a escolha de uma jurisdição neutra ou reconhecida como particularmente especializada ou célere. Pode também encontrar-se aí - e, mais em geral, no valor da autonomia privada - as razões para os instrumentos internacionais mais modernos não exigirem uma conexão objetiva com a jurisdição escolhida para o pacto ser admissível. É assim no Regulamento Bruxelas I /bis/, na Convenção de Lugano II, mas também, e por exemplo, na Convenção da Haia de 2005 os Acordos de Eleição do Foro. Não nos parece, por isso, adequado recorrer à ausência de conexões objetivas da situação privada internacional com Estados terceiros para interpretar (sem mais) a expressão "noutro tribunal competente (...) no estrangeiro" como sendo uma remissão (unicamente) para as demais normas atributivas de competência internacional do Regulamento Bruxelas I /bis/ e da Convenção Lugano II, pois há um risco significativo de tal não corresponder à intenção comum das partes. A referência ao princípio da autonomia privada e ao /effet utile/ parece apontar no sentido de que a /Cour de Cassation/ considera haver critérios autónomos de interpretação dos pactos de jurisdição, o que não nos parece ser uma questão que tenha sido decidida pelo TJ, nem no Acórdão em comentário nem na sua anterior jurisprudência. Uma interpretação que vise dar efeito útil aos pactos de jurisdição ao abrigo do Regulamento Bruxelas I /bis/ ou da Convenção de Lugano II aproxima-se (a nosso ver em demasia) de uma interpretação em conformidade com determinado(s) instrumento(s) normativo(s) [cite:O príncipio do efeito útil fundamenta uma interpretação do Direito nacional em conformidade com o Direito da União Europeia, em particular no que respeita à transposição de diretivas. Cf., neste sentido, @dacruzvilaca2013, pp. 287-289  *aditar doutrina*. Veja-se igualmente o Acórdão do TJ de 5 de outubro de 2004, /Pfeiffer/, C-397/01, EU:C:2004:584, considerando n.º 116, no qual se estabelece que o juiz nacional tem o dever de interpretar as disposições da ordem jurídica interna, utilizando todos os métodos de interpretação admitidos no Direito nacional, de modo conforme ao Direito da União, e o Acórdão do TJ de 16 de junho de 2005, /Pupino/, C-105/03, EU:C:2005:386, considerandos n.ºs 44 e 46, nos quais se indica que a obrigação de interpretação conforme do Direito nacional "(...) está limitada pelos princípios gerais de direito, nomeadamente os da segurança jurídica e da não retroactividade", não podendo, por isso, fundar uma interpretação /contra legem/ do Direito nacional]. Numa perspetiva de Direito comparado, a interpretação de contratos repousa, regra geral, numa combinação entre o critério /subjetivo/, que consiste na determinação da /real/ intenção comum das partes, e o critério /objetivo/ em que se interpreta as cláusulas contratuais partindo de uma perspetiva externa, como seja a de uma pessoa normal (artigo 236.º, n.º 1, do Código Civil português) ou a de uma pessoa razoável (artigo 8.º, n.º 2, da *CISG*, artigo 4.1, n.º 2, dos *PICC*, artigo 8:101, n.º 3 dos *DFCR II*) colocada na mesma posição das partes *[colocar nota de rodapé]*.

Fixar a interpretação de um pacto de jurisdição em conformidade com o que dispõe um determinado instrumento normativo parece uma solução que se afasta daqueles critérios, que são comummente adotados no Direito nacional dos Estados-Membros da União Europeia e também na maioria dos instrumentos que visam regular os contratos internacionais e, como tal, não nos parece ser a solução mais adequada. Até porque, mesmo que determinado pacto de jurisdição seja invalido de acordo com o Regulamento Bruxelas I /bis/, tal não acarreta, necessariamente, a invalidade ou ineficácia do pacto. Imagine-se que, no pacto de jurisdição que motivou o reenvio prejudicial, se apurava que a intenção comum das partes era a de permitir que o banco tivesse o direito de intentar também (eventuais) ações junto dos tribunais ingleses, atribuindo-lhes competência internacional. Esta intenção comum das partes, tornaria o pacto de jurisdição inadmissível à luz do Regulamento Bruxelas I /bis/ e da Convenção de Lugano (porque designava os tribunais de um Estado que não é um Estado-Membro nem um Estado Contratante), mas esse mesmo pacto poderia ainda ser válido e eficaz ao abrigo da Convenção da Haia de 2005 sobre Acordos de Eleição do Foro, uma vez que a União Europeia e o Reino Unido são Estados Contratantes desta convenção.

Merece, pensa-se, uma análise mais detalhada a indicação do TJ de que se o trecho "noutro tribunal competente (...) no estrangeiro" for intepretado "(...) no sentido de que designa também um ou vários (...)" Estados terceiros (que não são Estados-Membros ou Estados Contratantes da Convenção de Lugano II), então o pacto violaria os objetivos de previsibilidade, de transparência e de segurança jurídica referidos nos considerandos 15 e 16 do Regulamento Bruxelas I /bis/ (pois as normas do Regulamento Bruxelas I /bis/ ou da Convenção de Lugano II /não seriam suficientes/ para determinar quais os tribunais internacionalmente competentes ao abrigo do pacto) e existiria um risco de soluções divergentes resultantes da aplicação de outras normas atributivas de competência internacional vigente no Estado do foro[fn:33].

A primeira conclusão que se pode retirar desta indicação é a de que ela vale para os casos em que o pacto é /atributivo/ de jurisdição. Assim, e por exemplo, se um pacto de jurisdição assimétrico estipular que uma parte só pode intentar (eventuais) ações junto dos tribunais italianos e que a outra parte pode intentar (eventuais) ações junto dos tribunais italianos e ingleses, este pacto será contrário ao Regulamento Bruxelas I /bis/, por violar os seus objetivos de previsibilidade, de transparência e de segurança jurídica. O TJ não parece prever a possibilidade de redução ou conversão do pacto de jurisdição, pois conclui que nos casos em que o pacto /"designa também"/ (ou seja, atribui, adicionalmente, competência internacional) a tribunais de Estados terceiros, o pacto será contrário ao Regulamento Bruxelas I /bis/.

Questiona-se se esta linha argumentativa é também aplicável nos casos em que o pacto de jurisdição /não atribui/ competência internacional a tribunais de Estados terceiros, mas permite que uma das partes intente ações segundo as demais normas atributivas de competência internacional aplicáveis. Imagine-se os seguintes exemplos:

#+begin_quote
As partes expressamente acordam que a Parte A. apenas poderá intentar ações emergentes ou relacionadas com o presente contrato junto dos tribunais portugueses, com expressa renúncia a qualquer outro.
#+end_quote

#+begin_quote
As partes acordam expressamente em atribuir competência aos tribunais portugueses para julgar ações emergentes ou relacionadas com o presente contrato. Mais acordam que essa competência será exclusiva quando a ação seja intentada pela Parte A. e concorrencial (não exclusiva) quando a ação seja intentada pela Parte B.
#+end_quote

Por um lado, o pacto (por si só) não atribui competência internacional a tribunais de Estados terceiros. Por outro lado, e apesar disso, em ambos os exemplos pode ser necessário recorrer a normas atributivas de competência internacional que não sejam as do Regulamento Bruxelas I /bis/ ou da Convenção de Lugano II. Se o Parte A. tiver o seu domicílio ou sede num Estado terceiro e a ação for intentada pela Parte B., não serão aplicáveis as normas atributivas de competência internacional do Regulamento Bruxelas I /bis/ ou da Convenção de Lugano II, salvo em casos excecionais[fn:34]. Recorda-se que o TJ considerou que o pacto que motivou a questão prejudial cumpria a exigência de precisão constante do artigo 25.º se o trecho "[a SIL] reserva-se o direito de intentar uma ação contra o comprador noutro tribunal competente (...) no estrangeiro" fosse interpretado no sentido de uma remissão para /as normas gerais atributivas de competência internacional/ do Regulamento Bruxelas I /bis/ /ou/ da Convenção de Lugano II[fn:35].

Dir-se-á, em primeiro lugar, que se a questão é uma de interpretação daquele trecho do pacto de jurisdição que motivou a questão prejudicial, então a mesma não se coloca nos nossos exemplos. No nosso primeiro exemplo, as partes celebram um pacto atributivo de competência aos tribunais portugueses e privativo de competência aos tribunais dos demais Estados, mas limitado apenas às ações intentadas por uma das partes (a parte A.); no nosso segundo exemplo, as partes celebram um pacto atributivo de competência aos tribunais portugueses, mas estabelecem que o efeito privativo da competência dos demais Estados opera apenas para as ações intentadas por uma das partes (a parte A.). Não nos parece existir, nestes dois exemplos, qualquer trecho do pacto que suscite dúvidas interpretativas ou que deva ser interpretado como uma remissão para as normas gerais atributivas de competência internacional. Apesar disso, o resultado é /equivalente/: a competência internacional para dirimir um litígio intentado pela parte que não está vinculada (ao pacto, no primeiro exemplo, e ao efeito privativo do pacto, no segundo exemplo) é determinada segundo o Direito de Competência Internacional geral do Estado do foro, não tendo o pacto de jurisdição qualquer efeito /atributivo/ ou /privativo/ da jurisdição[fn:36].

A menção à necessidade de interpretar a parte final do pacto de jurisdição que motivou a questão prejudicial como "(...) uma remissão para as regras gerais de competência previstas pelo mesmo regulamento e pela referida convenção"[fn:37], suscita interrogações várias. Desde logo, a nível interpretativo, o que se deve entender por "regras gerais de competência" do Regulamento Bruxelas I /bis/ e da Convenção de Lugano II. Neste ponto o TJ afirma que:

#+begin_quote
há que salientar que um pacto atributivo de jurisdição que designa com suficiente precisão os tribunais dos Estados-Membros ou dos Estados parte da Convenção de Lugano II que podem ser chamados a pronunciar-se, nomeadamente, por um lado, um tribunal em particular e, por outro lado, outros tribunais competentes ao abrigo das disposições do capítulo II, secções 1 e 2, do Regulamento Bruxelas I-A e do título II, secções 1 e 2, desta convenção, cumpre a exigência de precisão que decorre do artigo 25.º, n.º 1, deste regulamento, bem como dos objetivos de previsibilidade, de transparência e de segurança jurídica enunciados nos considerandos 15 e 16 do referido regulamento.[fn:38]
#+end_quote

Nas disposições do capítulo II, secção I, do Regulamento Bruxelas I /bis/ e da Convenção de Lugano II prevê-se, respetivamente no artigo 6.º, n.º 1, e no artigo 4.º, n.º 1, que nos casos em que o requerido não tiver domicílio num Estado-Membro / Estado Contratante, a competência internacional não é, salvo casos excecionais, determinada pelas normas do Regulamento ou da Convenção, mas sim pelas demais normas atributivas de competência intenacional, de fonte interna ou supraestadual, vigentes no Estado-Membro / Estado Contratante onde a questão foi colocada.

A remissão para as regras gerais inclui o artigo 6.º, n.º 1, do Regulamento Bruxelas I /bis/ e o artigo 4.º, n.º 1, da Convenção de Lugano II, que remetem para o Direito da Competência Internacional, de fonte interna ou supraestadual, do Estado do foro? Pensa-se que não era essa a intenção do TJ, pois considerou contrário ao Regulamento Bruxelas I /bis/ os pactos em que as normas do Regulamento Bruxelas I /bis/ ou da Convenção de Lugano II /não seriam suficientes/ para determinar quais os tribunais internacionalmente competentes ao abrigo do pacto[fn:39]. Nesse caso, porém, fica em aberto a /validade/ de pactos de jurisdição assimétricos no contexto do Regulamento Bruxelas I /bis/ ou da Convenção de Lugano II, quando uma das partes tenha domicílio num Estado terceiro.

Em nossa opinião - que não nos parece inteiramente coincidente com a TJ - a questão deve resolver-se atendendo aos efeitos do pacto de jurisdição assimétrico. A exigência de precisão deve aferir-se tendo em conta, primacialmente, o efeito atributivo do pacto[cite:Discute-se, na doutrina, se o artigo 25.º é aplicável a um pacto que vise unicamente privar os tribunais de um Estado-Membro de competência para julgar litígios emergente ou relacionados com determinada situação jurídica. A posição maioritária é em sentido afirmativo, com fundamento na ideia de assegurar um tratamento uniforme dos pactos e evitar violações das normas de competência exclusiva e de proteção de partes mais vulneráveis (cf. Magnus /in/ @magnus2023, artigo 25.º, notas de margem 38 e 39). Nesses casos  - que não são os mais usuais na prática - a exigência de precisão terá de, naturalmente, aferir-se em função do efeito privativo do pacto.]. O efeito privativo do pacto de jurisdição, nos casos em que ele seja uma decorrência do carácter exclusivo do pacto, não nos parece relevante para aferir o cumprimento da exigência de precisão. O entendimento contrário, poderia até ter o efeito perverso de diminuir a previsibilidade e segurança jurídica do pacto, objetivos prosseguidos pelo Regulamento. Se, tendo em vista o cumprimento da exigência de precisão, as partes substituíssem a normal expressão "com expressa renúncia a qualquer outro" por "com expressa renúncia a qualquer outro tribunal de qualquer outro Estado-Membro ou Estado Contratante da Convenção de Lugano II", sucederia que - se uma das partes decidisse, mais tarde, intentar ação em Estado terceiro (que não é Estado-Membro ou Estado Contratante daquela Convenção), poder-se-ia, legitimamente, interpretar a intenção comum das partes como sendo no sentido de privar de competência /apenas/ os tribunais de Estados-Membros ou de Estados Contratantes que não o designado, /mas não/ privar de (eventual) competência os tribunais de outros Estados.

E, assim sendo, há que interpretar o pacto, de acordo com os critérios interpretativos da lei aplicável segundo o Direito de Conflitos do foro, para apurar se a designação (efeito atributivo de competência) cumpre a exigência de precisão. No caso do pacto que motivou o reenvio prejudicial, entendemos que o trecho que suscitou dúvidas interpretativos ("[a SIL] reserva-se o direito de intentar uma ação contra o comprador noutro tribunal competente (...) no estrangeiro") parece dever ser interpretado no sentido de que visa apenas expressamente estabelecer que o pacto, quando atribui competência aos tribunais de Brescia, não tem, para uma das partes (a SIL), carácter exclusivo. Esse trecho, por isso, não deve ser interpretado como uma convenção das partes que atribui competência a tribunais estrangeiros, por via do funcionamento das regras gerais. E, por isso, em nossa opinião, não suscita dificuldades quanto ao cumprimento da exigência de precisão.

* 5. Conclusões

O Acórdão sob comentário parece-nos relevante por várias ordens de razão. Desde logo porque nele o TJ concretiza o âmbito da norma de conflitos de introduzida no artigo 25.º. Depois de no Acórdão /Maersk/ ter concluído que a questão da oponibilidade de um pacto de jurisdição a um terceiro não é uma questão da validade substantiva do pacto[fn:44], esclarece agora que a norma de conflitos do artigo 25.º /não abrange/ as condições validade próprias, /mas apenas/ as causas gerais de nulidade de um contrato, como o erro, o dolo ou a violência, e a incapacidade de contratar. Esta conclusão parece-nos particularmente relevante para os objetivos de certeza e previsibilidade jurídicas prosseguidos pelo regime europeu de prorrogação de competência e também para o objetivo declarado da introdução da norma de conflitos: a aproximação ao regime consagrado na Convenção da Haia de 2005 sobre os Acordos de Eleição do Foro.

No que respeita aos (alegados) vícios de imprecisão e de desiquilíbrio entre as partes do pacto de jurisdição assimétrico, o TJ concluíu que os mesmos respeitam a requisitos autónomos estabelecidos no Regulamento Bruxelas I /bis/. Trata-se de uma conclusão muito segurança e que, por si só, aumenta a certeza e segurança jurídica na utilização de pactos de jurisdição assimétricos.

A análise efetuada pelo TJ em sede do (alegado) vício de imprecisão demonstra a importância da interpretação do pacto de jurisdição. Segundo jurisprudência constante do TJ, a interpretação do pacto de jurisdição compete  ao juiz nacional perante o qual o mesmo é invocado[fn:42]. Apesar disso, e sem prejuízo de avançar duas interpretações possíveis para o trecho final do pacto de jurisdição que motivou a questão prejudicial, o TJ não se pronunciou neste Acórdão sobre quais deveriam ser os critérios interpretativos desse negócio jurídico, se critérios autónomos a deduzir do Regulamento Bruxelas I /bis/ (ou do Direito da União Europeia) ou a determinar segundo a lei reguladora da interpretação dos pactos de jurisdição. Parece, no entanto, que atendendo à interpretação anteriormente feita do âmbito da norma de conflitos constante do artigo 25.º, que esta não deverá abranger a interpretação do pacto de jurisdição.

A menção à necessidade de interpretar a parte final do pacto de jurisdição que motivou a questão prejudicial como "(...) uma remissão para as regras gerais de competência previstas pelo mesmo regulamento e pela referida convenção"[fn:43], suscita a questão de saber o que se deve entender por "regras gerais de competência" do Regulamento Bruxelas I /bis/ e da Convenção de Lugano II. Crê-se que o TJ não pretendeu incluir o artigo 6.º, n.º 1, do Regulamento Bruxelas I /bis/, nem o artigo 4.º, n.º 1, da Convenção de Lugano II, pois estes preceitos remetem para as demais normas de Direito da Competência Internacional, de fonte interna ou supraestadual, do Estado do foro. A ser assim, porém, fica em aberto a /validade/ de pactos de jurisdição assimétricos no contexto do Regulamento Bruxelas I /bis/ ou da Convenção de Lugano II, quando uma das partes tenha domicílio num Estado terceiro.

A /Cour de Cassation/, na sequência do Acórdão sob comentário, entendeu que deveria interpretar a cláusula de acordo com os princípios da autonomia privada e do /effet utile/. E, relevando que a situação material subjacente não tinha qualquer conexão objetiva com Estados que não fossem Estados-Membros ou Estados-Contratantes da Convenção de Lugano II, interpretou a cláusula como sendo uma remissão para as demais regras de competência internacional desses dois instrumentos. Esta solução suscita-nos dúvidas desde logo porque há muito se assinala que podem existir razões para escolher uma jurisdição que não tenha qualquer conexão objetiva com a relação material subjacente ou as partes e porque uma interpretação que vise dar efeito útil aos pactos de jurisdição ao abrigo do Regulamento Bruxelas I /bis/ ou da Convenção de Lugano II aproxima-se (a nosso ver em demasia) de uma interpretação em conformidade com determinado(s) instrumento(s) normativo(s). Numa perspetiva de Direito comparado, a interpretação de contratos repousa, regra geral, numa combinação entre o critério /subjetivo/, que consiste na determinação da /real/ intenção comum das partes, e o critério /objetivo/ em que se interpreta as cláusulas contratuais partindo de uma perspetiva externa, como seja a de uma pessoa normal ou a de uma pessoa razoável colocada na mesma posição das partes.

Em nossa opinião - que não nos parece inteiramente coincidente com a TJ - a questão deve resolver-se atendendo aos efeitos do pacto de jurisdição assimétrico. A exigência de precisão deve aferir-se tendo em conta, primacialmente, o efeito atributivo do pacto. O efeito privativo do pacto de jurisdição, nos casos em que ele seja uma decorrência do carácter exclusivo do pacto, não nos parece relevante para aferir o cumprimento da exigência de precisão. Há, por isso, que interpretar o pacto para apurar se a designação (efeito atributivo de competência) cumpre a exigência de precisão. No caso do pacto que motivou o reenvio prejudicial, entendemos que o trecho que suscitou dúvidas interpretativos ("[a SIL] reserva-se o direito de intentar uma ação contra o comprador noutro tribunal competente (...) no estrangeiro") parece dever ser interpretado no sentido de que visa apenas estabelecer (expressamente) que o pacto, quando atribui competência aos tribunais de Brescia, não tem, para uma das partes (a SIL), carácter exclusivo. Ou seja, através desse trecho as partes não convencionaram atribuir competência internacional a um ou mais tribunais de um ou mais Estados, por via do funcionamento das regras gerais. E, por isso, em nossa opinião, o trecho não suscita dificuldades quanto ao cumprimento da exigência de precisão.


* Footnotes
[fn:44] Cf. Acórdão do TJ de 25 de abril de 2024, /Maersk/, C-345/22 a C-347/22, EU:C:2024:349, considerandos n.º 48 e 53.

[fn:43] Cf. considerando n.º 59.

[fn:42] Cf., no contexto da Convenção de Bruxelas, os Acórdãos do TJ de 10 de março de 1992, /Powell Duffryn/, C-214/89, EU:C:1992:115, considerando n.º 37, e de 2 de julho de 1997, /Benincasa/, C-269/95, EU:C:1997:337, considerando n.º 31; no contexto do Regulamento Bruxelas I, os Acórdãos do TJ de 21 de maio de 2015, /CDC Hydrogen Peroxide/, C-352/13, EU:C:2015:335, considerando n.º 67 e de 7 de julho de 2016, /Hőszig/, C-222/15, EU:C:2016:525, considerando n.º 28; e, no contexto do Regulamento Bruxelas I /bis/, o Acórdão do TJ de de 6 de outubro de 2021, /TOTO/, EU:C:2021:808, considerando n.º 51.

[fn:41] Nem se pronunciou na sua jurisprudência anterior.

[fn:40] Cf., no contexto da Convenção de Bruxelas, os Acórdãos do TJ de 10 de março de 1992, /Powell Duffryn/, C-214/89, EU:C:1992:115, considerando n.º 37, e de 2 de julho de 1997, /Benincasa/, C-269/95, EU:C:1997:337, considerando n.º 31; no contexto do Regulamento Bruxelas I, os Acórdãos do TJ de 21 de maio de 2015, /CDC Hydrogen Peroxide/, C-352/13, EU:C:2015:335, considerando n.º 67 e de 7 de julho de 2016, /Hőszig/, C-222/15, EU:C:2016:525, considerando n.º 28; e, no contexto do Regulamento Bruxelas I /bis/, o Acórdão do TJ de de 6 de outubro de 2021, /TOTO/, EU:C:2021:808, considerando n.º 51.

[fn:39] Cf. considerando n.º 60

[fn:38] Cf. considerando n.º 59.

[fn:37] Cf. considerando n.º 59.

[fn:36] No caso do segundo exemplo, o pacto só seria relevante se a parte B. decidisse intentar a ação junto dos tribunais portugueses, caso em que o pacto fundaria a competência internacional destes para dirimir o litígio.

[fn:35] Cf. considerando n.º 59.

[fn:34] Cf. artigo 6.º, n.º 1, do Regulamento Bruxelas I /bis/ e artigo 4.º, n.º 1, da Convenção de Lugano II.

[fn:33] Cf. considerando n.º 60.

[fn:32] Cf. Acórdão da /Cour de Cassation/, civile, Chambre civile 1, 17 de setembro de 2025, pourvoir n.º 22-12.965, ECLI:FR:CCASS:2025:C100581, considerandos n.ºs 18 e 19, disponível em https://www.courdecassation.fr/decision/68cba050e4abb8795b568fd7?search_api_fulltext=lastre&date_du=2025-09-01&date_au=2025-09-19&judilibre_juridiction=cc&op=Rechercher+sur+judilibre&previousdecisionpage=&previousdecisionindex=&nextdecisionpage=0&nextdecisionindex=1&previousdecisionpage=0&previousdecisionindex=1&nextdecisionpage=0&nextdecisionindex=3 e consultado pela última vez em 29 de setembro de 2025.

[fn:31] Cf. Acórdãos de 14 de dezembro de 1976, /Estasis Salotti/, 24/76, EU:C:1976:177, considerando n.º 7, e /Segoura/, 25/76, EU:C:1976:178, considerando n.° 6, de 20 de fevereiro de 1997, /MSG/, C-106/95, EU:C:1997:70, considerando n.º 15, e de 9 de novembro de 2000, /Coreck Maritime/, C-387/98, EU:C:2000:606, considerando n.º 13.

[fn:30] Regulamento (CE) n.º 864/2007 do Parlamento Europeu e do Conselho, de 11 de Julho de 2007, relativo à lei aplicável às obrigações extracontratuais (Roma II), publicado no JO L 199 de 31 de julho de 2007.

[fn:29] Cf. Acórdão da /Cour de Cassation/, civile, Chambre civile 1, 3 de outubro de 2018, pourvoir n.º 17-21.309, ECLI:FR:CCASS:2018:C100910, disponível em https://www.legifrance.gouv.fr/juri/id/JURITEXT000037495393?isSuggest=true e consultado pela última vez em 29 de setembro de 2025.

[fn:28] Sobre este Acórdão, cf. *[inserir doutrina]*;

[fn:27] Cf. Acórdão da /Cour de Cassation/, civile, Chambre civile 1, 26 de setembro de 2012, pourvoir n.º 11-26.2002, disponível em https://www.legifrance.gouv.fr/juri/id/JURITEXT000026431679?isSuggest=true e consultado pela última vez em 29 de setembro de 2025.

[fn:26] Considerandos n.ºs 64 e 65.

[fn:25] Considerando n.º 62.

[fn:24] Considerando n.º 60.

[fn:23] Considerando n.º 59.

[fn:22] Cosniderandos n.ºs 55 a 57.

[fn:21] Considerando n.º 68.

[fn:20] Considerando n.º 52.

[fn:19] Considerandos n.ºs 47 e 51.

[fn:18] Considerandos n.ºs 48 e 50.

[fn:17] Considerando n.º 45.

[fn:16] Considerando n.º 40.

[fn:15] Considerando n.º 39, invocando o Acórdão de 29 de julho de 2024, /FTI Touristik/, C-774/22, EU:C:2024:646, n.º 33 e jurisprudência aí referida.

[fn:14] Considerandos n.ºs 35 e 36.

[fn:13] Considerando n.º 34, invocando o Acórdão de 8 de março de 2018, /Saey Home & Garden/, C-64/17, EU:C:2018:173, n.º 24.

[fn:12] Considerando n.º 32.

[fn:11] Considerando n.º 31.

[fn:10] Considerando n.º 30.

[fn:9] Regulamento (UE) n.º 1215/2012 do Parlamento Europeu e do Conselho, de 12 de dezembro de 2012, relativo à competência judiciária, ao reconhecimento e à execução de decisões em matéria civil e comercial (reformulação), publicado no JO L 351 de 20 de dezembro de 2012. Os artigos subsequentes indicados sem indicação de fonte pertencem a este Regulamento, exceto se o contrário resultar inequivocamente do contexto.

[fn:8] Considerando n.º 27.

[fn:7] Considerando n.º 22.

[fn:6] Considerando n.º 21.

[fn:5] Considerando n.º 20.

[fn:4] Considerando n.º 19.

[fn:3] Considerando n.º 18.

[fn:2] Considerando n.º 17.

[fn:1] Considerando n.º 16 do Acórdão do Tribunal de Justiça da União Europeia  de 27 de fevereiro de 2025, /Società Italiana Lastre/, C-537/23, [[https://curia.europa.eu/juris/liste.jsf?nat=or&mat=or&pcs=Oor&jur=C%2CT%2CF&num=C-537%252F23&for=&jge=&dates=&language=pt&pro=&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&oqp=&td=%3BALL&avg=&lg=&page=1&cid=2486333][EU:C:2025:120]]. Os considerandos subsequentes citados sem indicação de fonte pertencem ao Acórdão que se comenta, exceto se o contrário resultar inequivocamente do contexto.
